# Generated by Django 4.2.7 on 2024-10-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_category_job_company_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_nature",
            field=models.CharField(
                choices=[
                    ("Full Time", "Full Time"),
                    ("Part Time", "Part Time"),
                    ("Remote", "Remote"),
                    ("Freelance", "Freelance"),
                    ("Internship", "internship"),
                ],
                max_length=20,
                verbose_name="Job Nature",
            ),
        ),
    ]
