# Generated by Django 4.2.7 on 2024-10-18 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0006_alter_job_location_alter_job_salary"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(max_length=5000, verbose_name="Cover Letter"),
                ),
                (
                    "nrc_number",
                    models.CharField(
                        help_text="Format: XXXXX XXXXX/XX/1",
                        max_length=15,
                        verbose_name="NRC Number",
                    ),
                ),
                (
                    "nrc_copy",
                    models.FileField(upload_to="nrcs/", verbose_name="NRC Copy"),
                ),
                (
                    "school_institution",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="School/Institution",
                    ),
                ),
                (
                    "linkedin_profile",
                    models.URLField(
                        blank=True, null=True, verbose_name="LinkedIn Profile"
                    ),
                ),
                ("age", models.PositiveIntegerField(verbose_name="Age")),
                (
                    "experience",
                    models.PositiveIntegerField(verbose_name="Years of Experience"),
                ),
                (
                    "resume",
                    models.FileField(upload_to="resumes/", verbose_name="Resume"),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Applied At"
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
                "unique_together": {("job", "applicant")},
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="certificates/", verbose_name="Certificate"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="jobs.jobapplication",
                    ),
                ),
            ],
        ),
    ]
