# Generated by Django 4.2.7 on 2024-10-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_jobapplication_certificate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobapplication",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="jobapplication",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="certificates",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="linked_in_profile",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="age",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="applied_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="experience",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="nrc_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="school_institution",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="Certificate",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="cover_letter",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="linkedin_profile",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="nrc_copy",
        ),
    ]
