# Generated by Django 4.2.7 on 2024-10-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_remove_jobapplication_certificates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="canceled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="selected_for_interview",
            field=models.BooleanField(default=False),
        ),
    ]
